services:
  - type: web
    name: finsight
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expensetracker.wsgi"
    envVars:
      - fromGroup: finsight-shared
      - key: DATABASE_URL
        fromDatabase:
          name: finsight-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: finsight-redis
          property: connectionString

  - type: worker
    name: finsight-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A expensetracker worker -l info"
    envVars:
      - fromGroup: finsight-shared
      - key: DATABASE_URL
        fromDatabase:
          name: finsight-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: finsight-redis
          property: connectionString

  - type: redis
    name: finsight-redis
    ipAllowList: []

databases:
  - name: finsight-db
    databaseName: finsight
    user: finsight_user

envVarGroups:
  - name: finsight-shared
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
