# Generated by Django 5.1.1 on 2026-05-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Stocks', 'Stocks'), ('MutualFund', 'MutualFund'), ('Gold', 'Gold'), ('FD', 'FD'), ('Crypto', 'Crypto'), ('RealEstate', 'RealEstate'), ('Other', 'Other')], max_length=50)),
                ('amount_invested', models.FloatField()),
                ('current_value', models.FloatField()),
                ('date_invested', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
