# Generated by Django 5.1.1 on 2026-05-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
