# Generated by Django 5.1.1 on 2026-05-15 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_delete_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Mutual Fund', 'Mutual Fund'), ('Fixed Deposit', 'Fixed Deposit'), ('Gold', 'Gold'), ('REIT', 'REIT'), ('Crypto', 'Crypto'), ('ETF', 'ETF'), ('Bond', 'Bond'), ('Options', 'Options'), ('Forex', 'Forex'), ('Other', 'Other')], max_length=50)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
