# Generated by Django 5.1.1 on 2026-05-01 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenselimit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselimit',
            name='monthly_expense_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expenselimit',
            name='weekly_expense_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expenselimit',
            name='yearly_expense_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenselimit',
            name='daily_expense_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('date_triggered', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
