# Generated by Django 5.1.1 on 2026-05-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_pendingrecurringexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pendingrecurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
