# Generated by Django 5.1.1 on 2026-05-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0002_source_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
