# Generated by Django 5.1.1 on 2026-05-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0003_alter_userincome_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincome',
            options={'ordering': ['-date']},
        ),
    ]
